version = "0.2.0" # vampires_dpp version

name = "20221230_PDS111"
target = "PDS 111"
directory = "/Volumes/mlucas SSD1/2022/20221230"
output_directory = "/Volumes/mlucas SSD1/2022/20221230/20221230_PDS111/processed"
filenames = "PDS111_01*.fits"
frame_centers = [[122, 128], [122, 128]] # cam 1, cam 2 centers (x, y)

[calibration]
output_directory = "calibrated"
deinterleave = true

[calibration.darks]
filenames = [
    "skies_40ms_em300_00_750-50_EmptySlot_000_cam1.fits",
    "skies_40ms_em300_00_750-50_EmptySlot_000_cam2.fits",
]

[registration]
method = "com"
output_directory = "registered"

[collapsing]
output_directory = "collapsed"

[derotate]
output_directory = "derotated"

[polarimetry]
method = "triplediff"
force = true

[polarimetry.ip]
radius = 3 # radius of circular aperture